### ISSUE TITLE
Buffering non stop

### ISSUE THREAD

**Issue by Scottm382** [lucasharding/antenna#4] opened 2017-01-10 16:49 UTC
Loaded antenna thru ipwnstore and all channels buffer bad. When I use Ustinov on Jodi it's flawless. Any suggestions?  It's not our router or hardware. Thx

**Comment by Ylinen** [comment] 2017-01-12 19:12
I am seeing the following as well.  When I try to play a DVR I get a Spinning wheel and it never plays.

Then on some LIVE TV; I will get the Spinning Wheel after 10 to 15 seconds.  Then sometimes the channel plays fine.

My USTVNow works fine on my PC browser and through my Smart TV Browser.

Hope the developer can come on to this forum and see if he can ID for us.

**Comment by rhfide** [comment] 2017-01-28 18:45
The same here. Spinning wheel all the time. In simulator on Xcode it works, but not on ATV 4. Sometimes it workes on Fox channel, but that's it. Any ideas ?

**Comment by Ylinen** [comment] 2017-01-28 18:58
I had hoped the developer would come back and provide some help.  APP is very well designed and could be great.

Because it sometimes works on LIVE, it must be some problem with the way the code is or a problem with the stream that interrupts the playing.  Some live streams work fine.  I don't know if the DVR stream is different from LIVE and that is the problem there.  I am not an Apple Developer.  This Apple TV and an old IPAD are the only Apple products I have.

**Comment by GavinLa** [comment] 2017-01-28 19:26
I actually have no problem playing live streams. In fact, it works so well that I've stopped subscribing to Sling. However, the DVR doesn't work for me. I just get the spinning wheel as if it's buffering.

I'd like to troubleshoot but not sure where to start and as the live streams work fine, I'm still very pleased.

**Comment by Ylinen** [comment] 2017-01-28 19:29
What version of IOS and version of Apple TV are you using?  Interesting you never get the spinning wheel on Live TV.  Looks like we confirmed the DVR does not work.  If I could get this working well, I would be on just two apps.  Antenna and Playstation Vue.  Would be just perfect.

**Comment by Scottm382** [comment] 2017-01-29 01:17
blockquote, div.yahoo_quoted { margin-left: 0 !important; border-left:1px #715FFA solid !important; padding-left:1ex !important; background-color:white !important; } I'm on tvOS 10.1.1. Just upgraded but the previous version didn't work either. I'm watching live tv in antenna app and it buffers all the time. Works for a minute then just spinning wheel. But in kodi ustvnow works great. 
I also use PlayStation vue. Best service so far. 
Any ideas how to fix antenna app?


Sent from Yahoo Mail for iPhone


On Saturday, January 28, 2017, 2:29 PM, Ylinen <notifications@github.com> wrote:


What version of IOS and version of Apple TV are you using? Interesting you never get the spinning wheel on Live TV. Looks like we confirmed the DVR does not work. If I could get this working well, I would be on just two apps. Antenna and Playstation Vue. Would be just perfect.

**Comment by GavinLa** [comment] 2017-02-02 11:48
I’m currently on the latest tvOS, version 10.1.1. It worked fine for me on the previous version too.

What way did you install? Did you sign the prebuilt IPA or build from source? Maybe there’s some difference there, although I’ve no idea what it would be.

Finally, I’m on a paid USTVnow account, are you? Maybe there’s some difference there too?

**Comment by Ylinen** [comment] 2017-02-02 21:28
Gavin;
I too am on tvOS 10.1.1 on an Apple TV 4.  I installed the prebuilt IPA using impactor 9.38 .  I too have a USTVnow paid account.

Does the DVR work for you?  I always get a spinning wheel.  Then on LIVETV I get the spinning wheel periodically.  I have 90/90 speed with 9ms latency on my network connection.

**Comment by GavinLa** [comment] 2017-02-03 12:24
No, the DVR doesn't work for me anymore. I *think* it initially worked to an extent - from memory, it crashed when trying to add a show to the DVR but I was able to watch shows that had already been set up on the website.

Live TV works really well for me - I do get the buffering spinning wheel now and then, but no more than when I watched USTVNow on the Roku streaming stick. I am often able to watch Live TV for several hours without buffering. Sometimes, when USTVNow is overloaded, I get buffering messages more frequently.

But, in summary, apart from the DVR, it generally works better than on the Roku and the interface is 100 times nicer.

**Comment by lucasharding** [comment] 2017-02-09 05:59
Sorry, wasn't able to investigate until now. If you update to [this release](https://github.com/lucasharding/antenna/releases/tag/v1.0.1) streaming and DVR playback should be fixed.

I've updated the streaming to use a new API that the USTVnow website uses, and it is much more reliable.

**Closed by lucasharding** 2017-02-09 05:59 UTC
